package:
  name: gnutls
  version: 3.8.5
  epoch: 1
  description: TLS protocol implementation
  copyright:
    - license: LGPL-2.1-or-later
  dependencies:
    runtime:
      - nettle

# creates a new var that contains only the major and minor version to be used in the fetch URL
# e.g. 2.46.0 will create a new var mangled-package-version=2.46
var-transforms:
  - from: ${{package.version}}
    match: (\d+\.\d+)\.\d+
    replace: $1
    to: mangled-package-version

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - coreutils
      - gettext-dev
      - gperf
      - gtk-doc
      - libev-dev
      - libkcapi-dev
      - libtasn1-dev
      - libtool
      - libunistring-dev
      - linux-headers
      - nettle-dev
      - p11-kit-dev
      - patch
      - pkgconf-dev
      - texinfo
      - wget
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/gnutls/gnutls.git
      tag: ${{package.version}}
      expected-commit: 49f4ae2109b7cc969539b90be92a5844bbe7b322

  - runs: |
      ./bootstrap

  - runs: |
      LIBS="-lgmp"  \
      ./configure \
        --host=${{host.triplet.gnu}} \
        --build=${{host.triplet.gnu}} \
        --prefix=/usr \
        --sysconfdir=/etc \
        --libdir=/usr/lib \
        --mandir=/usr/share/man \
        --infodir=/usr/share/info \
        --localstatedir=/var \
        --enable-ktls \
        --disable-openssl-compatibility \
        --disable-rpath \
        --disable-static \
        --disable-guile \
        --disable-valgrind-tests

  - uses: autoconf/make

  - uses: autoconf/make-install

  # Fix underlinking problem with GNUTLS depending on P11-KIT.
  - runs: |
      echo 'Requires: p11-kit-1' >> "${{targets.destdir}}"/usr/lib/pkgconfig/gnutls.pc

  - uses: strip

subpackages:
  - name: gnutls-doc
    pipeline:
      - uses: split/manpages
      - uses: split/infodir
    description: gnutls manpages

  - name: gnutls-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - gnutls
        - nettle-dev
        - p11-kit-dev
        - libtasn1-dev
    description: gnutls dev

  - name: gnutls-utils
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr
          mv ${{targets.destdir}}/usr/bin ${{targets.subpkgdir}}/usr/
    description: Command line tools for TLS protocol

  - name: gnutls-c++
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib
          mv ${{targets.destdir}}/usr/lib/lib*xx.so.* ${{targets.subpkgdir}}/usr/lib/
    description: The C++ interface to GnuTLS

update:
  enabled: true
  ignore-regex-patterns:
    - "^gnutls.*"
  github:
    identifier: gnutls/gnutls
    use-tag: true
