#nolint:valid-pipeline-git-checkout-tag
package:
  name: iperf
  version: 2.2.0
  epoch: 1
  description: A tool to measure IP bandwidth using UDP or TCP
  copyright:
    - license: NCSA

var-transforms:
  - from: ${{package.version}}
    match: \.
    replace: "-"
    to: mangled-package-version

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - linux-headers

pipeline:
  - uses: git-checkout
    with:
      repository: https://git.code.sf.net/p/iperf2/code
      # The iperf2 code doesn't seem to track using tags
      branch: ${{vars.mangled-package-version}}
      expected-commit: 59ccf3c5aac51873cd99f0e423f7ac3023aa9c2a

  - uses: autoconf/configure
    with:
      opts: |
        --build=$CBUILD \
        --host=$CHOST \
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --infodir=/usr/share/info

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 1388
