package:
  name: libbsd
  version: 0.12.2
  epoch: 2
  description: commonly-used BSD functions not implemented by all libcs
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libmd-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.freedesktop.org/libbsd/libbsd.git
      tag: ${{package.version}}
      expected-commit: 04a24db27ad1572f766bad772cdd9c146e6d9cf0

  - runs: |
      ./autogen

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libbsd-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libmd-dev
        - libbsd
    description: libbsd dev

  - name: libbsd-doc
    pipeline:
      - uses: split/manpages
    description: libbsd manpages

update:
  enabled: true
  release-monitor:
    identifier: 1567
