package:
  name: libgcrypt
  version: 1.11.0
  epoch: 0
  description: General purpose crypto library based on the code used in GnuPG
  copyright:
    - license: LGPL-2.1-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - gettext-dev
      - libgpg-error-dev
      - libtool
      - texinfo

pipeline:
  - uses: git-checkout
    with:
      repository: git://git.gnupg.org/libgcrypt.git
      tag: libgcrypt-${{package.version}}
      expected-commit: 9d94d7846cde272b8b1519ba96e53967bf0b90d2

  - runs: |
      ./autogen.sh --force

  - uses: autoconf/configure
    with:
      opts: |
        --enable-maintainer-mode

  - uses: autoconf/make

  - uses: autoconf/make-install

  - runs: |
      rm -f "${{targets.destdir}}"/usr/share/info/dir

  - uses: strip

subpackages:
  - name: libgcrypt-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libgcrypt
        - libgpg-error-dev
    description: libgcrypt dev

  - name: libgcrypt-doc
    pipeline:
      - uses: split/manpages
    description: libgcrypt manpages

update:
  enabled: true
  release-monitor:
    identifier: 1623
